# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1490, 689)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftSpace = QtWidgets.QWidget(self.centralwidget)
        self.leftSpace.setObjectName("leftSpace")
        self.horizontalLayout.addWidget(self.leftSpace)
        self.sidebar = QtWidgets.QWidget(self.centralwidget)
        self.sidebar.setMinimumSize(QtCore.QSize(250, 600))
        self.sidebar.setMaximumSize(QtCore.QSize(250, 600))
        self.sidebar.setAutoFillBackground(True)
        self.sidebar.setStyleSheet("sidebar {border: 1px solid;}")
        self.sidebar.setObjectName("sidebar")
        self.clearButton = QtWidgets.QPushButton(self.sidebar)
        self.clearButton.setGeometry(QtCore.QRect(20, 30, 91, 41))
        self.clearButton.setObjectName("clearButton")
        self.penSizeSlider = QtWidgets.QSlider(self.sidebar)
        self.penSizeSlider.setGeometry(QtCore.QRect(20, 120, 160, 22))
        self.penSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.penSizeSlider.setObjectName("penSizeSlider")
        self.penSizeLabel = QtWidgets.QLabel(self.sidebar)
        self.penSizeLabel.setGeometry(QtCore.QRect(20, 90, 111, 16))
        self.penSizeLabel.setObjectName("penSizeLabel")
        self.penColorLabel = QtWidgets.QLabel(self.sidebar)
        self.penColorLabel.setGeometry(QtCore.QRect(20, 160, 101, 16))
        self.penColorLabel.setObjectName("penColorLabel")
        self.penColorButton = QtWidgets.QPushButton(self.sidebar)
        self.penColorButton.setGeometry(QtCore.QRect(20, 190, 91, 41))
        self.penColorButton.setObjectName("penColorButton")
        self.penHardSoft = QtWidgets.QPushButton(self.sidebar)
        self.penHardSoft.setGeometry(QtCore.QRect(20, 280, 61, 41))
        self.penHardSoft.setObjectName("penHardSoft")
        self.penStyleLabel = QtWidgets.QLabel(self.sidebar)
        self.penStyleLabel.setGeometry(QtCore.QRect(20, 250, 101, 16))
        self.penStyleLabel.setObjectName("penStyleLabel")
        self.penEraserButton = QtWidgets.QPushButton(self.sidebar)
        self.penEraserButton.setGeometry(QtCore.QRect(130, 30, 91, 41))
        self.penEraserButton.setObjectName("penEraserButton")
        self.eraserSizeSlider = QtWidgets.QSlider(self.sidebar)
        self.eraserSizeSlider.setGeometry(QtCore.QRect(20, 380, 160, 22))
        self.eraserSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.eraserSizeSlider.setObjectName("eraserSizeSlider")
        self.eraserSizeLabel = QtWidgets.QLabel(self.sidebar)
        self.eraserSizeLabel.setGeometry(QtCore.QRect(20, 350, 121, 16))
        self.eraserSizeLabel.setObjectName("eraserSizeLabel")
        self.penTypeCombo = QtWidgets.QComboBox(self.sidebar)
        self.penTypeCombo.setGeometry(QtCore.QRect(20, 450, 161, 22))
        self.penTypeCombo.setObjectName("penTypeCombo")
        self.penTypeCombo.addItem("")
        self.penTypeCombo.addItem("")
        self.penTypeCombo.addItem("")
        self.penTypeCombo.addItem("")
        self.penTypeCombo.addItem("")
        self.penTypeCombo.addItem("")
        self.penTypeCombo.addItem("")
        self.penTypeCombo.addItem("")
        self.penTypeCombo.addItem("")
        self.penTypeCombo.addItem("")
        self.penTypeCombo.addItem("")
        self.penTypeCombo.addItem("")
        self.penTypeCombo.addItem("")
        self.penTypeCombo.addItem("")
        self.penTypeLabel = QtWidgets.QLabel(self.sidebar)
        self.penTypeLabel.setGeometry(QtCore.QRect(20, 420, 101, 16))
        self.penTypeLabel.setObjectName("penTypeLabel")
        self.horizontalLayout.addWidget(self.sidebar)
        self.canvas = Canvas(self.centralwidget)
        self.canvas.setMinimumSize(QtCore.QSize(600, 600))
        self.canvas.setMaximumSize(QtCore.QSize(600, 600))
        self.canvas.setBaseSize(QtCore.QSize(600, 600))
        self.canvas.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.canvas.setAutoFillBackground(True)
        self.canvas.setStyleSheet("")
        self.canvas.setObjectName("canvas")
        self.horizontalLayout.addWidget(self.canvas, 0, QtCore.Qt.AlignLeft)
        self.rightSpace = QtWidgets.QWidget(self.centralwidget)
        self.rightSpace.setObjectName("rightSpace")
        self.horizontalLayout.addWidget(self.rightSpace)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionSaveAs)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.clearButton.setText(_translate("MainWindow", "Clear canvas"))
        self.penSizeLabel.setText(_translate("MainWindow", "Current pen size(1):"))
        self.penColorLabel.setText(_translate("MainWindow", "Current pen color:"))
        self.penColorButton.setText(_translate("MainWindow", "Choose"))
        self.penHardSoft.setText(_translate("MainWindow", "Hard"))
        self.penStyleLabel.setText(_translate("MainWindow", "Current pen style:"))
        self.penEraserButton.setText(_translate("MainWindow", "Pen"))
        self.eraserSizeLabel.setText(_translate("MainWindow", "Current eraser size(2):"))
        self.penTypeCombo.setItemText(0, _translate("MainWindow", "Default"))
        self.penTypeCombo.setItemText(1, _translate("MainWindow", "Dense 1"))
        self.penTypeCombo.setItemText(2, _translate("MainWindow", "Dense 2"))
        self.penTypeCombo.setItemText(3, _translate("MainWindow", "Dense 3"))
        self.penTypeCombo.setItemText(4, _translate("MainWindow", "Dense 4"))
        self.penTypeCombo.setItemText(5, _translate("MainWindow", "Dense 5"))
        self.penTypeCombo.setItemText(6, _translate("MainWindow", "Dense 6"))
        self.penTypeCombo.setItemText(7, _translate("MainWindow", "Dense 7"))
        self.penTypeCombo.setItemText(8, _translate("MainWindow", "Horizontal"))
        self.penTypeCombo.setItemText(9, _translate("MainWindow", "Vertical"))
        self.penTypeCombo.setItemText(10, _translate("MainWindow", "Cross"))
        self.penTypeCombo.setItemText(11, _translate("MainWindow", "BDiagonal"))
        self.penTypeCombo.setItemText(12, _translate("MainWindow", "FDiagonal"))
        self.penTypeCombo.setItemText(13, _translate("MainWindow", "DiagonalCross"))
        self.penTypeLabel.setText(_translate("MainWindow", "Current pen type:"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save As.."))
        self.actionSaveAs.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setToolTip(_translate("MainWindow", "Save File"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))

from canvas import Canvas
